// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/arac/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/arac">> = Specific
  const handler = {} as typeof import("../../src/app/arac/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ayarlar/numara-sablonlari/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ayarlar/numara-sablonlari">> = Specific
  const handler = {} as typeof import("../../src/app/ayarlar/numara-sablonlari/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ayarlar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ayarlar">> = Specific
  const handler = {} as typeof import("../../src/app/ayarlar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/banka-havale/gelen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/banka-havale/gelen">> = Specific
  const handler = {} as typeof import("../../src/app/banka-havale/gelen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/banka-havale/giden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/banka-havale/giden">> = Specific
  const handler = {} as typeof import("../../src/app/banka-havale/giden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/banka-havale/silinen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/banka-havale/silinen">> = Specific
  const handler = {} as typeof import("../../src/app/banka-havale/silinen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bekleme-salonu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bekleme-salonu">> = Specific
  const handler = {} as typeof import("../../src/app/bekleme-salonu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bordro/cek/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bordro/cek">> = Specific
  const handler = {} as typeof import("../../src/app/bordro/cek/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bordro/senet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bordro/senet">> = Specific
  const handler = {} as typeof import("../../src/app/bordro/senet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bordro/silinen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bordro/silinen">> = Specific
  const handler = {} as typeof import("../../src/app/bordro/silinen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bordro/vade-takvim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bordro/vade-takvim">> = Specific
  const handler = {} as typeof import("../../src/app/bordro/vade-takvim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cari/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cari/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/cari/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cari/fatura-kapatma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cari/fatura-kapatma">> = Specific
  const handler = {} as typeof import("../../src/app/cari/fatura-kapatma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cari/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cari">> = Specific
  const handler = {} as typeof import("../../src/app/cari/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cek-senet-kasasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cek-senet-kasasi">> = Specific
  const handler = {} as typeof import("../../src/app/cek-senet-kasasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/depo/depolar/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/depo/depolar/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/depo/depolar/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/depo/depolar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/depo/depolar">> = Specific
  const handler = {} as typeof import("../../src/app/depo/depolar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/depo/islemler/put-away/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/depo/islemler/put-away">> = Specific
  const handler = {} as typeof import("../../src/app/depo/islemler/put-away/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/depo/islemler/transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/depo/islemler/transfer">> = Specific
  const handler = {} as typeof import("../../src/app/depo/islemler/transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/depo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/depo">> = Specific
  const handler = {} as typeof import("../../src/app/depo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/depo/raporlar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/depo/raporlar">> = Specific
  const handler = {} as typeof import("../../src/app/depo/raporlar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/efatura/gelen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/efatura/gelen">> = Specific
  const handler = {} as typeof import("../../src/app/efatura/gelen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/alis/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/alis/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/alis/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/alis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/alis">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/alis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/alis/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/alis/print/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/alis/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/alis/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/alis/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/alis/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/arsiv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/arsiv">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/arsiv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/iade/alis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/iade/alis">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/iade/alis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/iade/alis/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/iade/alis/print/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/iade/alis/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/iade/alis/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/iade/alis/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/iade/alis/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/iade/satis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/iade/satis">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/iade/satis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/iade/satis/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/iade/satis/print/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/iade/satis/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/iade/satis/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/iade/satis/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/iade/satis/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/satis/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/satis/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/satis/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/satis/malzeme-hazirlama/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/satis/malzeme-hazirlama/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/satis/malzeme-hazirlama/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/satis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/satis">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/satis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/satis/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/satis/print/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/satis/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fatura/satis/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fatura/satis/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/fatura/satis/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ik/personel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ik/personel">> = Specific
  const handler = {} as typeof import("../../src/app/ik/personel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kasa/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kasa/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/kasa/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kasa/[id]/transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kasa/[id]/transfer">> = Specific
  const handler = {} as typeof import("../../src/app/kasa/[id]/transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/kasa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kasa">> = Specific
  const handler = {} as typeof import("../../src/app/kasa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/masraf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/masraf">> = Specific
  const handler = {} as typeof import("../../src/app/masraf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/purchase-orders/[id]/create-invoice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/[id]/create-invoice">> = Specific
  const handler = {} as typeof import("../../src/app/purchase-orders/[id]/create-invoice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/purchase-orders/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/purchase-orders/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/purchase-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/purchase-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/purchase-orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/new">> = Specific
  const handler = {} as typeof import("../../src/app/purchase-orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders">> = Specific
  const handler = {} as typeof import("../../src/app/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/raporlama/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/raporlama">> = Specific
  const handler = {} as typeof import("../../src/app/raporlama/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/satin-alma-irsaliyesi/[id]/duzenle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/satin-alma-irsaliyesi/[id]/duzenle">> = Specific
  const handler = {} as typeof import("../../src/app/satin-alma-irsaliyesi/[id]/duzenle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/satin-alma-irsaliyesi/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/satin-alma-irsaliyesi/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/satin-alma-irsaliyesi/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/satin-alma-irsaliyesi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/satin-alma-irsaliyesi">> = Specific
  const handler = {} as typeof import("../../src/app/satin-alma-irsaliyesi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/satin-alma-irsaliyesi/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/satin-alma-irsaliyesi/print/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/satin-alma-irsaliyesi/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/satin-alma-irsaliyesi/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/satin-alma-irsaliyesi/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/satin-alma-irsaliyesi/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/satis-irsaliyesi/[id]/duzenle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/satis-irsaliyesi/[id]/duzenle">> = Specific
  const handler = {} as typeof import("../../src/app/satis-irsaliyesi/[id]/duzenle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/satis-irsaliyesi/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/satis-irsaliyesi/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/satis-irsaliyesi/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/satis-irsaliyesi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/satis-irsaliyesi">> = Specific
  const handler = {} as typeof import("../../src/app/satis-irsaliyesi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/satis-irsaliyesi/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/satis-irsaliyesi/print/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/satis-irsaliyesi/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/satis-irsaliyesi/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/satis-irsaliyesi/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/satis-irsaliyesi/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sayim/liste/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sayim/liste">> = Specific
  const handler = {} as typeof import("../../src/app/sayim/liste/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sayim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sayim">> = Specific
  const handler = {} as typeof import("../../src/app/sayim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sayim/raf-bazli/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sayim/raf-bazli">> = Specific
  const handler = {} as typeof import("../../src/app/sayim/raf-bazli/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sayim/urun-bazli/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sayim/urun-bazli">> = Specific
  const handler = {} as typeof import("../../src/app/sayim/urun-bazli/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servis/araclar/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servis/araclar/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/servis/araclar/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servis/araclar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servis/araclar">> = Specific
  const handler = {} as typeof import("../../src/app/servis/araclar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servis/araclar/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servis/araclar/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/servis/araclar/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servis/atolye-panosu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servis/atolye-panosu">> = Specific
  const handler = {} as typeof import("../../src/app/servis/atolye-panosu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servis/bakim-hatirlatmalari/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servis/bakim-hatirlatmalari">> = Specific
  const handler = {} as typeof import("../../src/app/servis/bakim-hatirlatmalari/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servis/is-emirleri/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servis/is-emirleri/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/servis/is-emirleri/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servis/is-emirleri/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servis/is-emirleri">> = Specific
  const handler = {} as typeof import("../../src/app/servis/is-emirleri/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servis/is-emirleri/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servis/is-emirleri/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/servis/is-emirleri/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servis">> = Specific
  const handler = {} as typeof import("../../src/app/servis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servis/teknisyenler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servis/teknisyenler">> = Specific
  const handler = {} as typeof import("../../src/app/servis/teknisyenler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/hazirla/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/hazirla/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/hazirla/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/hazirlama-listesi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/hazirlama-listesi">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/hazirlama-listesi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/satin-alma/detay/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/satin-alma/detay/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/satin-alma/detay/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/satin-alma/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/satin-alma/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/satin-alma/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/satin-alma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/satin-alma">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/satin-alma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/satin-alma/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/satin-alma/print/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/satin-alma/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/satin-alma/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/satin-alma/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/satin-alma/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/satis/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/satis/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/satis/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/satis/hazirlama/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/satis/hazirlama/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/satis/hazirlama/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/satis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/satis">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/satis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/satis/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/satis/print/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/satis/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/siparis/satis/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/siparis/satis/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/siparis/satis/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/birim-setleri/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok/birim-setleri">> = Specific
  const handler = {} as typeof import("../../src/app/stok/birim-setleri/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/kategori-yonetimi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok/kategori-yonetimi">> = Specific
  const handler = {} as typeof import("../../src/app/stok/kategori-yonetimi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/maliyet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok/maliyet">> = Specific
  const handler = {} as typeof import("../../src/app/stok/maliyet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/malzeme-hareketleri/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok/malzeme-hareketleri">> = Specific
  const handler = {} as typeof import("../../src/app/stok/malzeme-hareketleri/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/malzeme-listesi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok/malzeme-listesi">> = Specific
  const handler = {} as typeof import("../../src/app/stok/malzeme-listesi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/marka-yonetimi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok/marka-yonetimi">> = Specific
  const handler = {} as typeof import("../../src/app/stok/marka-yonetimi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok">> = Specific
  const handler = {} as typeof import("../../src/app/stok/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/satin-alma-fiyatlari/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok/satin-alma-fiyatlari">> = Specific
  const handler = {} as typeof import("../../src/app/stok/satin-alma-fiyatlari/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/satis-fiyatlari/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok/satis-fiyatlari">> = Specific
  const handler = {} as typeof import("../../src/app/stok/satis-fiyatlari/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/toplu-satis-fiyat-guncelle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok/toplu-satis-fiyat-guncelle">> = Specific
  const handler = {} as typeof import("../../src/app/stok/toplu-satis-fiyat-guncelle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stok/urun-eslestirme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stok/urun-eslestirme">> = Specific
  const handler = {} as typeof import("../../src/app/stok/urun-eslestirme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tahsilat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tahsilat">> = Specific
  const handler = {} as typeof import("../../src/app/tahsilat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tahsilat/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tahsilat/print/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/tahsilat/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teklif/satin-alma/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teklif/satin-alma/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/teklif/satin-alma/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teklif/satin-alma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teklif/satin-alma">> = Specific
  const handler = {} as typeof import("../../src/app/teklif/satin-alma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teklif/satin-alma/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teklif/satin-alma/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/teklif/satin-alma/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teklif/satis/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teklif/satis/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/teklif/satis/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teklif/satis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teklif/satis">> = Specific
  const handler = {} as typeof import("../../src/app/teklif/satis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teklif/satis/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teklif/satis/print/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/teklif/satis/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teklif/satis/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teklif/satis/yeni">> = Specific
  const handler = {} as typeof import("../../src/app/teklif/satis/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vade-analiz/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vade-analiz">> = Specific
  const handler = {} as typeof import("../../src/app/vade-analiz/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/veri-aktarim/cari-hesap-aktarim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/veri-aktarim/cari-hesap-aktarim">> = Specific
  const handler = {} as typeof import("../../src/app/veri-aktarim/cari-hesap-aktarim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/veri-aktarim/malzeme-aktarim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/veri-aktarim/malzeme-aktarim">> = Specific
  const handler = {} as typeof import("../../src/app/veri-aktarim/malzeme-aktarim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/veri-aktarim/satin-alma-fiyat-aktarim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/veri-aktarim/satin-alma-fiyat-aktarim">> = Specific
  const handler = {} as typeof import("../../src/app/veri-aktarim/satin-alma-fiyat-aktarim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/veri-aktarim/satis-fiyat-aktarim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/veri-aktarim/satis-fiyat-aktarim">> = Specific
  const handler = {} as typeof import("../../src/app/veri-aktarim/satis-fiyat-aktarim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hizli/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hizli">> = Specific
  const handler = {} as typeof import("../../src/app/api/hizli/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hizli/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hizli/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/hizli/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/bekleme-salonu/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/bekleme-salonu">> = Specific
  const handler = {} as typeof import("../../src/app/bekleme-salonu/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
