// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(main)/accounts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/accounts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/accounts/invoice-closing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/invoice-closing">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/accounts/invoice-closing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/accounts/reports/borc-alacak/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts/reports/borc-alacak">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/accounts/reports/borc-alacak/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/authorization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/authorization">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/authorization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/authorization/roller/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/authorization/roller/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/authorization/roller/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/authorization/roller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/authorization/roller">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/authorization/roller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/bank-transfer/gelen/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-transfer/gelen/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/bank-transfer/gelen/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/bank-transfer/gelen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-transfer/gelen">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/bank-transfer/gelen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/bank-transfer/giden/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-transfer/giden/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/bank-transfer/giden/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/bank-transfer/giden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-transfer/giden">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/bank-transfer/giden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/bank-transfer/silinen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-transfer/silinen">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/bank-transfer/silinen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/bank/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/bank/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/bank/credit-operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/credit-operations">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/bank/credit-operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/bank/hesap/[hesapId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/hesap/[hesapId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/bank/hesap/[hesapId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/bank/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/bank/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/cash/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cash/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/cash/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/cash/[id]/transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cash/[id]/transfer">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/cash/[id]/transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/cash/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cash">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/cash/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/checks-promissory-notes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checks-promissory-notes/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/checks-promissory-notes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/checks-promissory-notes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checks-promissory-notes">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/checks-promissory-notes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/collection/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collection/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/collection/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/collection/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collection">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/collection/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/collection/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collection/print/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/collection/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/company-vehicles/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company-vehicles/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/company-vehicles/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/company-vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company-vehicles">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/company-vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/data-import/cari-hesap-aktarim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-import/cari-hesap-aktarim">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/data-import/cari-hesap-aktarim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/data-import/malzeme-aktarim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-import/malzeme-aktarim">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/data-import/malzeme-aktarim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/data-import/satin-alma-fiyat-aktarim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-import/satin-alma-fiyat-aktarim">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/data-import/satin-alma-fiyat-aktarim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/data-import/satis-fiyat-aktarim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-import/satis-fiyat-aktarim">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/data-import/satis-fiyat-aktarim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/e-invoice/gelen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/e-invoice/gelen">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/e-invoice/gelen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/expense/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expense/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/expense/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/expense/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expense">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/expense/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/hr/advances/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/advances">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/hr/advances/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/hr/personel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/personel">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/hr/personel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/hr/salary-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/salary-management">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/hr/salary-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/inventory-count/liste/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory-count/liste">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/inventory-count/liste/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/inventory-count/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory-count">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/inventory-count/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/inventory-count/raf-bazli/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory-count/raf-bazli">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/inventory-count/raf-bazli/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/inventory-count/urun-bazli/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory-count/urun-bazli">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/inventory-count/urun-bazli/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/archive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/archive">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/archive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/profitability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/profitability">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/profitability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/purchase/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/purchase/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/purchase/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/purchase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/purchase">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/purchase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/purchase/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/purchase/print/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/purchase/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/purchase/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/purchase/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/purchase/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/return/purchase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/return/purchase">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/return/purchase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/return/purchase/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/return/purchase/print/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/return/purchase/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/return/purchase/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/return/purchase/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/return/purchase/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/return/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/return/sales">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/return/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/return/sales/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/return/sales/print/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/return/sales/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/return/sales/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/return/sales/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/return/sales/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/sales/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/sales/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/sales/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/sales/malzeme-hazirlama/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/sales/malzeme-hazirlama/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/sales/malzeme-hazirlama/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/sales">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/sales/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/sales/print/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/sales/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/invoice/sales/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/sales/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/sales/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/management/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/management/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/maturity-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maturity-analysis">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/maturity-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/hazirla/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/hazirla/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/hazirla/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/preparation-list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/preparation-list">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/preparation-list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/satin-alma/detay/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/satin-alma/detay/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/satin-alma/detay/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/satin-alma/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/satin-alma/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/satin-alma/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/satin-alma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/satin-alma">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/satin-alma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/satin-alma/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/satin-alma/print/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/satin-alma/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/satin-alma/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/satin-alma/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/satin-alma/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/satis/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/satis/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/satis/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/satis/hazirlama/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/satis/hazirlama/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/satis/hazirlama/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/satis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/satis">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/satis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/satis/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/satis/print/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/satis/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/orders/satis/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/satis/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/orders/satis/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/payroll/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/payroll/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/payroll/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payroll/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/payroll/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pos">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/purchase-delivery-note/[id]/duzenle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-delivery-note/[id]/duzenle">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/purchase-delivery-note/[id]/duzenle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/purchase-delivery-note/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-delivery-note/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/purchase-delivery-note/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/purchase-delivery-note/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-delivery-note">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/purchase-delivery-note/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/purchase-delivery-note/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-delivery-note/print/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/purchase-delivery-note/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/purchase-delivery-note/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-delivery-note/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/purchase-delivery-note/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/purchase-orders/[id]/create-invoice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/[id]/create-invoice">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/purchase-orders/[id]/create-invoice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/purchase-orders/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/purchase-orders/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/purchase-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/purchase-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/purchase-orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/purchase-orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/quotes/satin-alma/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/satin-alma/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/quotes/satin-alma/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/quotes/satin-alma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/satin-alma">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/quotes/satin-alma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/quotes/satin-alma/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/satin-alma/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/quotes/satin-alma/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/quotes/satis/duzenle/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/satis/duzenle/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/quotes/satis/duzenle/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/quotes/satis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/satis">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/quotes/satis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/quotes/satis/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/satis/print/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/quotes/satis/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/quotes/satis/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/satis/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/quotes/satis/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/reporting/cari-risk-limitleri/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reporting/cari-risk-limitleri">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/reporting/cari-risk-limitleri/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/reporting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reporting">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/reporting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/reporting/satis-elemani/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reporting/satis-elemani">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/reporting/satis-elemani/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/sales-delivery-note/[id]/duzenle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-delivery-note/[id]/duzenle">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/sales-delivery-note/[id]/duzenle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/sales-delivery-note/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-delivery-note/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/sales-delivery-note/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/sales-delivery-note/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-delivery-note">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/sales-delivery-note/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/sales-delivery-note/print/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-delivery-note/print/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/sales-delivery-note/print/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/sales-delivery-note/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-delivery-note/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/sales-delivery-note/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/accounting-records/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/accounting-records/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/accounting-records/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/accounting-records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/accounting-records">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/accounting-records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/customer-vehicles/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/customer-vehicles/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/customer-vehicles/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/customer-vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/customer-vehicles">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/customer-vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/invoices/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/invoices/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/invoices">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/part-procurement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/part-procurement">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/part-procurement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/part-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/part-requests">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/part-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/technicians/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/technicians">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/technicians/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/work-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/work-orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/work-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/work-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/work-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/work-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/work-orders/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/work-orders/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/work-orders/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/settings/company-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/company-settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/settings/company-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/settings/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/logs">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/settings/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/settings/number-templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/number-templates">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/settings/number-templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/settings/parameters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/parameters">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/settings/parameters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/settings/quick-menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/quick-menu">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/settings/quick-menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/settings/sales-staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/sales-staff">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/settings/sales-staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/[id]/ambar-toplamlari/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/[id]/ambar-toplamlari">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/[id]/ambar-toplamlari/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/brand-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/brand-management">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/brand-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/bulk-sales-price-update/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/bulk-sales-price-update">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/bulk-sales-price-update/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/category-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/category-management">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/category-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/costing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/costing">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/costing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/critical-stock-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/critical-stock-management">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/critical-stock-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/material-list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/material-list">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/material-list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/material-movements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/material-movements">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/material-movements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/product-matching/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/product-matching">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/product-matching/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/purchase-prices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/purchase-prices">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/purchase-prices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/sales-prices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/sales-prices">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/sales-prices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/stock/unit-sets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/unit-sets">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/stock/unit-sets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/warehouse/operations/put-away/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/operations/put-away">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/warehouse/operations/put-away/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/warehouse/operations/transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/operations/transfer">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/warehouse/operations/transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/warehouse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/warehouse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/warehouse/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/warehouse/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/warehouse/stock-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/stock-report">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/warehouse/stock-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/warehouse/transfer-note/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/transfer-note/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/warehouse/transfer-note/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/warehouse/transfer-note/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/transfer-note">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/warehouse/transfer-note/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/warehouse/transfer-note/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/transfer-note/yeni">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/warehouse/transfer-note/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/warehouse/warehouses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/warehouses/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/warehouse/warehouses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/warehouse/warehouses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/warehouses">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/warehouse/warehouses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[...path]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/cookies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/cookies">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/cookies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/hizli/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hizli">> = Specific
  const handler = {} as typeof import("../../../src/app/api/hizli/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/hizli/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hizli/test">> = Specific
  const handler = {} as typeof import("../../../src/app/api/hizli/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/work-order/[id]/send-for-approval/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/work-order/[id]/send-for-approval">> = Specific
  const handler = {} as typeof import("../../../src/app/api/work-order/[id]/send-for-approval/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/work-order/assignment-users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/work-order/assignment-users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/work-order/assignment-users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(main)/invoice/sales/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/invoice/sales">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/invoice/sales/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/service/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/service">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/service/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
