-- Add BEKLEMEDE and PARCALAR_TEDARIK_EDILDI to VehicleServiceStatus
ALTER TYPE "VehicleServiceStatus" ADD VALUE IF NOT EXISTS 'BEKLEMEDE';
ALTER TYPE "VehicleServiceStatus" ADD VALUE IF NOT EXISTS 'PARCALAR_TEDARIK_EDILDI';

-- Add PART_WAITING and PARTS_SUPPLIED to WorkOrderStatus
ALTER TYPE "WorkOrderStatus" ADD VALUE IF NOT EXISTS 'PART_WAITING';
ALTER TYPE "WorkOrderStatus" ADD VALUE IF NOT EXISTS 'PARTS_SUPPLIED';

-- Change work order default status to WAITING_DIAGNOSIS (Beklemede - ilk aşama)
ALTER TABLE "work_orders" ALTER COLUMN "status" SET DEFAULT 'WAITING_DIAGNOSIS';
