var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/stok/toplu-satis-fiyat-guncelle/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5446cdd6._.js")
R.c("server/chunks/ssr/2036a_next_dist_3152e3d6._.js")
R.c("server/chunks/ssr/www_panel-stage_client_35a8cf25._.js")
R.c("server/chunks/ssr/[root-of-the-server]__14846e6a._.js")
R.c("server/chunks/ssr/2036a_next_dist_27bc84d0._.js")
R.c("server/chunks/ssr/2036a_next_dist_f855de64._.js")
R.c("server/chunks/ssr/2036a_next_dist_client_components_builtin_global-error_afb0b78f.js")
R.c("server/chunks/ssr/www_panel-stage_client_src_app_8ff757a2._.js")
R.c("server/chunks/ssr/2036a_next_dist_client_components_7e402b5b._.js")
R.c("server/chunks/ssr/2036a_next_dist_client_components_builtin_forbidden_df178c69.js")
R.c("server/chunks/ssr/2036a_next_dist_client_components_builtin_unauthorized_9919f94e.js")
R.c("server/chunks/ssr/6af17__next-internal_server_app_stok_toplu-satis-fiyat-guncelle_page_actions_155f7beb.js")
R.m(347906)
module.exports=R.m(347906).exports
