var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/depo/islemler/transfer/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__64c57dce._.js")
R.c("server/chunks/ssr/2036a_next_dist_3152e3d6._.js")
R.c("server/chunks/ssr/www_panel-stage_client_b3f63a69._.js")
R.c("server/chunks/ssr/[root-of-the-server]__14846e6a._.js")
R.c("server/chunks/ssr/2036a_next_dist_27bc84d0._.js")
R.c("server/chunks/ssr/2036a_next_dist_f855de64._.js")
R.c("server/chunks/ssr/2036a_next_dist_client_components_builtin_global-error_afb0b78f.js")
R.c("server/chunks/ssr/www_panel-stage_client_src_app_8ff757a2._.js")
R.c("server/chunks/ssr/2036a_next_dist_client_components_7e402b5b._.js")
R.c("server/chunks/ssr/2036a_next_dist_client_components_builtin_forbidden_df178c69.js")
R.c("server/chunks/ssr/2036a_next_dist_client_components_builtin_unauthorized_9919f94e.js")
R.c("server/chunks/ssr/09f98_client__next-internal_server_app_depo_islemler_transfer_page_actions_b995bc5e.js")
R.m(657284)
module.exports=R.m(657284).exports
