-- Add new WorkOrderStatus enum values: VEHICLE_READY, CLOSED_WITHOUT_INVOICE
ALTER TYPE "WorkOrderStatus" ADD VALUE IF NOT EXISTS 'VEHICLE_READY';
ALTER TYPE "WorkOrderStatus" ADD VALUE IF NOT EXISTS 'CLOSED_WITHOUT_INVOICE';
