export const QK = {
    journals: (filters?: object) => ['journals', filters] as const,
    journal: (id: string) => ['journal', id] as const,
    checks: (filters?: object) => ['checks', filters] as const,
    checkStatsSummary: () => ['check-stats-summary'] as const,
    checkStatsAging: () => ['check-stats-aging'] as const,
    checkStatsCashflow: () => ['check-stats-cashflow'] as const,
    check: (id: string) => ['check', id] as const,
    checkTimeline: (id: string) => ['check-timeline', id] as const,
    checkGlEntries: (id: string) => ['check-gl-entries', id] as const,
    checkDocuments: (id: string) => ['check-documents', id] as const,
    checkBillReports: (key: string) => ['check-bill-reports', key] as const,
    /** checks-promissory-notes/upcoming — pencere gün sayısı */
    checkUpcoming: (days: number) => ['check-upcoming', days] as const,
    checkOverdue: () => ['check-overdue'] as const,
    checkAtRisk: (minScore: number) => ['check-at-risk', minScore] as const,
    checkEndorsements: (id: string) => ['check-endorsements', id] as const,
    checkCollections: (id: string) => ['check-collections', id] as const,
    accounts: (search?: string) => ['accounts', search] as const,
    bankAccounts: (filters?: object) => ['bank-accounts', filters] as const,
    cashboxes: (filters?: object) => ['cashboxes', filters] as const,
    reportPortfolio: () => ['report-portfolio'] as const,
    reportMaturity: () => ['report-maturity'] as const,
    reportAccount: () => ['report-account'] as const,
    reportCollection: () => ['report-collection'] as const,
};
