export enum CollectionType {
    COLLECTION = 'COLLECTION',
    PAYMENT = 'PAYMENT'
}

export enum PaymentMethod {
    CASH = 'CASH',
    CREDIT_CARD = 'CREDIT_CARD',
    BANK_TRANSFER = 'BANK_TRANSFER',
    CHECK = 'CHECK',
    PROMISSORY_NOTE = 'PROMISSORY_NOTE',
    GIFT_CARD = 'GIFT_CARD',
    LOAN_ACCOUNT = 'LOAN_ACCOUNT'
}
